/* Code generated by cmd/cgo; DO NOT EDIT. */

#ifndef LIBBASE64_GO_H
#define LIBBASE64_GO_H
#endif

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

int libbase64_go_nts__getLastErrorCode(void){
	return 0;
}

char* libbase64_go_nts__getErrorDescription(int errno){
	return NULL;
}

char* libbase64_go_nts__BASE64_encode_std(char* inputText){
	return NULL;
}

char* libbase64_go_nts__BASE64_decode_std(char* inputText){
	return NULL;
}

char* libbase64_go_nts__BASE64_encode_url(char* inputText){
	return NULL;
}

char* libbase64_go_nts__BASE64_encode_raw(char* inputText){
	return NULL;
}

void libbase64_go__FreeResult(char* ptr){
	return;
}

char* libbase64_go__Version(void){
	return "0.0.1";
}

char* libbase64_go__Version_go(void){
	return "go1.0.0";
}

#ifdef __cplusplus
}
#endif
