/* Code generated by cmd/cgo; DO NOT EDIT. */

#ifndef LIBBASE64_GO_H
#define LIBBASE64_GO_H
#endif

#include "constants.h"

#ifdef __cplusplus
extern "C" {
#endif

extern int libbase64_go_nts__getLastErrorCode(void);
extern char* libbase64_go_nts__getErrorDescription(int errno);
extern char* libbase64_go_nts__BASE64_encode_std(char* inputText);
extern char* libbase64_go_nts__BASE64_decode_std(char* inputText);
extern char* libbase64_go_nts__BASE64_encode_url(char* inputText);
extern char* libbase64_go_nts__BASE64_encode_raw(char* inputText);
extern void libbase64_go__FreeResult(char* ptr);
extern char* libbase64_go__Version(void);
extern char* libbase64_go__Version_go(void);

#ifdef __cplusplus
}
#endif
